apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac/service-account.yaml
- rbac/role.yaml
- rbac/role-binding.yaml
- secrets/secrets.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: schedule-queue-system