apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../components/rabbitmq
- ../../components/django-scheduler

patches:
- path: rabbitmq-config.yaml
- path: django-config.yaml

configMapGenerator:
- name: app-config
  namespace: schedule-queue-system
  literals:
  - DEBUG=True
  - ENVIRONMENT=development
