apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: schedule-queue-system
spec:
  type: ClusterIP
  selector:
    app: django-scheduler
  ports:
  - port: 80
    targetPort: 8000