apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: schedule-queue-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      serviceAccountName: sqs-sa
      containers:
      - name: celery-beat
        image: localhost/django-scheduler:latest
        imagePullPolicy: Never
        command: ["celery", "-A", "scheduler_core", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: DJANGO_SECRET_KEY
        - name: RABBITMQ_HOST
          value: "rabbitmq-service.schedule-queue-system.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: RABBITMQ_PASSWORD